### PR TITLE
Add setup.py

### PR DESCRIPTION
**Pull request by bobatsar**
- Restructure project for setup.py based on
  https://blog.ionelmc.ro/2014/05/25/python-packaging/#the-structure
- Add basic setup.py to allow installation e.g. via pip from github

### CODE REVIEW

**Comment by bobatsar** [comment]
Hey @SloMusti @NejcKle, I added a basic `setup.py` and restructured the project a bit to be installable via pip. Could you please merge my PR or do you have any concerns?

**Comment by NejcKle** [comment]
> Hey @SloMusti @NejcKle, I added a basic `setup.py` and restructured the project a bit to be installable via pip. Could you please merge my PR or do you have any concerns?

Hi @bobatsar, we will do it in a short while. Thank you very much for contributing!

**Comment by wlgrd** [comment]
Any updates?

**Comment by NejcKle** [comment]
@bobatsar We have added your changes to the repo. Thank you for contributing!

**Pull request merged**
